version: "3.9"

services:
  bookmarker-db:
    image: postgres:14-alpine

    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "15432:5432"

    # DB가 실행되고 초기화 되고 healthy Check
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - bookmarker-network

networks:
  bookmarker-network:
    driver: bridge