# ==========================================
# 1단계 : 의존성 설치 전용 이미지
# ==========================================

# Node.js 24 Alpine Linux 기반 이미지 사용
FROM node:22-alpine AS deps

# 일부 npm 패키지가 필요로 하는 glibc 호환 라이브러리 설치
RUN apk add --no-cache libc6-compat

# 컨테이너 내부 작업 폴더 생성
WORKDIR /app

# package.json, package-lock.json 복사
# 의존성 설치를 위해 먼저 복사한다.
COPY package*.json ./

# node_modules 설치
# package-lock.json 기준으로 정확한 버전 설치
RUN npm ci --omit=dev



# ==========================================
# 2단계 : 빌드 전용 이미지
# ==========================================

FROM node:22-alpine AS builder

WORKDIR /app

# 프로젝트 전체 복사
COPY . .

# 1단계에서 설치한 node_modules 복사
COPY --from=deps /app/node_modules ./node_modules

# COPY .env.local .env.local

# Next.js 빌드 실행
# 결과물은 .next 폴더에 생성된다.
RUN npm run build


# ==========================================
# 3단계 : 실행 전용 이미지
# ==========================================

FROM node:22-alpine AS runner

WORKDIR /app

# 운영 환경 지정
ENV NODE_ENV=production

# 보안상 root 사용 금지
# 그룹 생성
RUN addgroup -S nodejs

# 사용자 생성
RUN adduser -S nextjs -G nodejs

# ==========================================
# 실행에 필요한 파일만 복사
# ==========================================

# 빌드 결과물
COPY --from=builder /app/.next ./.next

# 정적 파일
COPY --from=builder /app/public ./public

COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next

# 실행에 필요한 패키지
COPY --from=builder /app/node_modules ./node_modules

# package.json
COPY --from=builder /app/package.json ./package.json
# 환경설정 파일은 .env.local 실행 폴더로 복사
COPY --from=builder /app/.env.local ./

# 일반 사용자 권한으로 실행
USER nextjs

# Next.js 기본 포트
EXPOSE 3000

# 컨테이너 시작 시 실행
CMD ["npm", "start"]