# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

# 어떤 Branch라도 코드가 push될 때마다 workflow가 실행되도록 함
on:
  push:
    branches:
      - "**"

# Jobs를 통해서 workflow 단계 만들어 준다
jobs:
  build-bookmark-api:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./bookmarker-api

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      # Maven Build 작업 시 실행 권한 부여
      - name: Build with Maven
        run: |
          chmod +x mvnw
          ./mvnw verify

      # Docker 이미지 빌드 및 Push
      - name: Build and Push Image
        if: github.ref == 'refs/heads/main'
        run: |
          ./mvnw clean package jib:dockerBuild -DskipTests

          docker login \
            -u ${{ secrets.DOCKER_USERNAME }} \
            -p ${{ secrets.DOCKER_PASSWORD }}

          docker build \
            -t myimage:latest .

          docker tag myimage:latest \
            ${{ secrets.DOCKER_USERNAME }}/bookmarker-api:latest

          docker push \
            ${{ secrets.DOCKER_USERNAME }}/bookmarker-api:latest

#######################################################
#         bookmar-ui-nextjs 빌드 및 docker 배포         #
#######################################################
  build-bookmarker-ui:
    name: Build bookmarker-ui
    runs-on: ubuntu-latest
    defaults:
      # 배포된 git repository의 폴더명
      run:
        working-directory: ./bookmark-ui-nextjs
    steps:
      #코드체크아웃
      - name: Checkout repository
        uses: actions/checkout@v5

      #Node.js 설정
      - name: Setup Node.js 22
        uses: actions/setup-node@v5
        with:
          node-version: 22
      
      #의존성 설치
      - name: Install dependecies
        run: npm ci

      #Next.js 빌드
      - name: Next.js Build
        run: npm run build
      
      #.env.local 파일 설정
      # 복사해서 사용하지 않는 이유는 UI의 .gitignore 파일은 .env* 파일을 제외 한다
      # 파일을 작성해서 넣어 준다 echo 문서를 만들어 준다
      - name: Create .env 파일 생성
        run: |
          echo "SERVER_SIDE_API_BASE_URL=${{ secrets.SERVER_SIDE_API_BASE_URL }}" > .env.local
          echo "NEXT_PUBLIC_CLIENT_SIDE_API_BASE_URL=${{ secrets.NEXT_PUBLIC_CLIENT_SIDE_API_BASE_URL }}" >> .env.local

      # 메인 브렌치 일경우 Docker 이미지 빌드 및 배포
      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Build and Push Docker image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile.ui -t ${{ secrets.DOCKER_USERNAME }}/bookmark-ui-nextjs .
          docker push ${{ secrets.DOCKER_USERNAME }}/bookmark-ui-nextjs

######################
# k8s 배포 job
# github action에서 build => docker hub 완료된 후에 server에 요청해서 변경된 사항을 k8s가 kubectl 명령어를 통해서 새로 고침 (rollout)
#
# 1) Github Actions에서 server의 SSH로 접속(계정/비밀번호 - secret)
# 2) kubectl 설정 파일 지정
# 3) 리소스 읽어와야함 확인 deployment가 있는 pods 이름이 맞는지
# 4) 기존의 Pod를 종료 -> 새로운 Pod를 생성
# 5) 상태확인 Pod가 정상 상태 될 때까지 대기
##
  deploy:
    name: Deploy to Server k8s
    runs-on: ubuntu-latest

    needs:
      - build-bookmark-api
      - build-bookmarker-ui

    if: github.ref == 'refs/heads/main'

    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v0.1.7

        with:
          host: ${{ secrets.SERVER_IP }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}

          script: |
            export KUBECONFIG=/home/ubuntu/.kube/config
            kubectl get nodes
            kubectl get pods
            kubectl apply -f /k8s

            echo "==== Deployment 재시작 ===="

            kubectl rollout restart deployment/bookmarker-api
            kubectl rollout restart deployment/bookmarker-ui-deployment
      
            echo "==== 새로운 Pod 실행 대기 ===="
            kubectl rollout status deployment/bookmarker-api
            kubectl rollout status deployment/bookmarker-ui-deployment

            echo "==== k8s 배포 완료 ===="




